#!/bin/bash
# ═══════════════════════════════════════════════════════════════════════════════
#  workspace.sh — Workspace target handler
#
#  Called by install.sh when target = workspace.
#  Runs AFTER core.sh + mode extras have installed all agents, skills, etc.
#
#  This file handles workspace-specific setup:
#    - Validate/create workspace-manifest.json
#    - Generate .code-workspace file for VS Code multi-root
#    - Initialization stamp
#    - .gitignore rules
#
#  Sourced by install.sh. Never run directly.
#
#  Provides:
#    install_workspace()  — called by install.sh
#
#  Expected variables (set by install.sh before calling):
#    WORKSPACE_NAME      — workspace name (e.g. "mortgage-ipa-workspace")
#    SERVICE_REPOS       — comma-separated repo paths (may be empty)
#    REPOS_ARE_SUBDIRS   — "true" if repos are subdirectories, "false" if external
# ═══════════════════════════════════════════════════════════════════════════════

install_workspace() {
  print_section "Workspace configuration"

  local ws_name="${WORKSPACE_NAME:-$(basename "$TARGET_DIR")}"

  # ════════════════════════════════════════════════════════════════════════════
  #  workspace-manifest.json
  # ════════════════════════════════════════════════════════════════════════════
  local manifest_path="$TARGET_DIR/.github/copilot/workspace-manifest.json"
  mkdir -p "$TARGET_DIR/.github/copilot"

  if [ ! -f "$manifest_path" ]; then
    # Build services array from SERVICE_REPOS if provided
    local services_json="[]"
    if [ -n "${SERVICE_REPOS:-}" ]; then
      services_json="["
      local first=true
      IFS=',' read -ra repos <<< "$SERVICE_REPOS"
      for repo_path in "${repos[@]}"; do
        repo_path=$(echo "$repo_path" | xargs)  # trim whitespace
        local repo_name
        repo_name=$(basename "$repo_path")
        if [ "$first" = true ]; then
          first=false
        else
          services_json+=","
        fi
        if [ "${REPOS_ARE_SUBDIRS:-true}" = "true" ]; then
          services_json+="
      {\"name\": \"$repo_name\", \"path\": \"./$repo_name\"}"
        else
          services_json+="
      {\"name\": \"$repo_name\", \"path\": \"$repo_path\"}"
        fi
      done
      services_json+="
    ]"
    fi

    cat > "$manifest_path" << MANIFESTEOF
{
  "workspace": "$ws_name",
  "version": "1.0",
  "initializedAt": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
  "services": $services_json,
  "notes": "Generated by SDLC Copilot Template installer"
}
MANIFESTEOF
    echo "  [add]  .github/copilot/workspace-manifest.json"
  else
    echo "  [skip] .github/copilot/workspace-manifest.json"
  fi

  # ════════════════════════════════════════════════════════════════════════════
  #  .code-workspace file (VS Code multi-root workspace)
  # ════════════════════════════════════════════════════════════════════════════
  local ws_file="$TARGET_DIR/${ws_name}.code-workspace"

  if [ ! -f "$ws_file" ]; then
    # Build folders array
    local folders_json="[
    {\"name\": \"workspace-config\", \"path\": \".\"}"

    if [ -n "${SERVICE_REPOS:-}" ]; then
      IFS=',' read -ra repos <<< "$SERVICE_REPOS"
      for repo_path in "${repos[@]}"; do
        repo_path=$(echo "$repo_path" | xargs)
        local repo_name
        repo_name=$(basename "$repo_path")
        if [ "${REPOS_ARE_SUBDIRS:-true}" = "true" ]; then
          folders_json+=",
    {\"name\": \"$repo_name\", \"path\": \"./$repo_name\"}"
        else
          folders_json+=",
    {\"name\": \"$repo_name\", \"path\": \"$repo_path\"}"
        fi
      done
    fi

    folders_json+="
  ]"

    cat > "$ws_file" << WSEOF
{
  "folders": $folders_json,
  "settings": {
    "chat.agent.enabled": true,
    "chat.useAgentSkills": true,
    "github.copilot.chat.codeGeneration.useInstructionFiles": true
  }
}
WSEOF
    echo "  [add]  ${ws_name}.code-workspace"
  else
    echo "  [skip] ${ws_name}.code-workspace"
  fi

  # ════════════════════════════════════════════════════════════════════════════
  #  Initialization stamp
  # ════════════════════════════════════════════════════════════════════════════
  local init_flag="$TARGET_DIR/.github/copilot/.initialized"
  if [ ! -f "$init_flag" ]; then
    echo "{\"workspace\":\"$ws_name\",\"initializedAt\":\"$(date -u +%Y-%m-%dT%H:%M:%SZ)\",\"plugin\":\"workspace\"}" \
      > "$init_flag"
    echo "  [add]  .github/copilot/.initialized"
  else
    echo "  [skip] .github/copilot/.initialized (already initialized)"
  fi

  echo ""
}
