#!/bin/bash
# ═══════════════════════════════════════════════════════════════════════════════
#  workspace.sh — Workspace target handler
#
#  Called by install.sh when target = workspace.
#  Runs AFTER core.sh + mode extras have installed all agents, skills, etc.
#
#  This file handles workspace-specific setup:
#    - Validate/create workspace-manifest.json
#    - Generate .code-workspace file for VS Code multi-root
#    - Initialization stamp
#    - .gitignore rules
#
#  Sourced by install.sh. Never run directly.
#
#  Provides:
#    install_workspace()  — called by install.sh
#
#  Expected variables (set by install.sh before calling):
#    WORKSPACE_NAME      — workspace name (e.g. "mortgage-ipa-workspace")
#    SERVICE_REPOS       — comma-separated repo paths (may be empty)
#    REPOS_ARE_SUBDIRS   — "true" if repos are subdirectories, "false" if external
# ═══════════════════════════════════════════════════════════════════════════════

install_workspace() {
  print_section "Workspace configuration"

  local ws_name="${WORKSPACE_NAME:-$(basename "$TARGET_DIR")}"

  # ════════════════════════════════════════════════════════════════════════════
  #  workspace-manifest.json
  # ════════════════════════════════════════════════════════════════════════════
  local manifest_path="$TARGET_DIR/.github/copilot/workspace-manifest.json"
  mkdir -p "$TARGET_DIR/.github/copilot"

  if [ ! -f "$manifest_path" ]; then
    # Build services array from SERVICE_REPOS if provided
    local services_json="[]"
    if [ -n "${SERVICE_REPOS:-}" ]; then
      services_json="["
      local first=true
      IFS=',' read -ra repos <<< "$SERVICE_REPOS"
      for repo_path in "${repos[@]}"; do
        repo_path=$(echo "$repo_path" | xargs)  # trim whitespace
        local repo_name
        repo_name=$(basename "$repo_path")
        if [ "$first" = true ]; then
          first=false
        else
          services_json+=","
        fi
        if [ "${REPOS_ARE_SUBDIRS:-true}" = "true" ]; then
          services_json+="
      {\"name\": \"$repo_name\", \"path\": \"./$repo_name\"}"
        else
          services_json+="
      {\"name\": \"$repo_name\", \"path\": \"$repo_path\"}"
        fi
      done
      services_json+="
    ]"
    fi

    cat > "$manifest_path" << MANIFESTEOF
{
  "workspace": "$ws_name",
  "version": "1.0",
  "initializedAt": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
  "services": $services_json,
  "notes": "Generated by SDLC Copilot Template installer"
}
MANIFESTEOF
    echo "  [add]  .github/copilot/workspace-manifest.json"
  else
    echo "  [skip] .github/copilot/workspace-manifest.json"
  fi

  # ════════════════════════════════════════════════════════════════════════════
  #  .code-workspace file (VS Code multi-root workspace)
  # ════════════════════════════════════════════════════════════════════════════
  local ws_file="$TARGET_DIR/${ws_name}.code-workspace"

  if [ ! -f "$ws_file" ]; then
    # ── Build folders array ───────────────────────────────────────────────────
    # Service repos go FIRST so developers see them at the top of the Explorer.
    # The workspace-config folder (this repo) goes last with a ⚙️ prefix.
    local folders_json="["
    local has_services=false

    if [ -n "${SERVICE_REPOS:-}" ]; then
      has_services=true
      IFS=',' read -ra repos <<< "$SERVICE_REPOS"
      local first_svc=true
      for repo_path in "${repos[@]}"; do
        repo_path=$(echo "$repo_path" | xargs)
        local repo_name
        repo_name=$(basename "$repo_path")
        if [ "$first_svc" = true ]; then
          first_svc=false
        else
          folders_json+=","
        fi
        if [ "${REPOS_ARE_SUBDIRS:-true}" = "true" ]; then
          folders_json+="
    {\"path\": \"./$repo_name\", \"name\": \"$repo_name\"}"
        else
          folders_json+="
    {\"path\": \"$repo_path\", \"name\": \"$repo_name\"}"
        fi
      done
      folders_json+=","
    fi

    # Workspace-config always last
    folders_json+="
    {\"path\": \".\", \"name\": \"⚙️ $ws_name\"}
  ]"

    cat > "$ws_file" << WSEOF
{
  "folders": $folders_json,
  "settings": {
    "github.copilot.chat.agent.enabled": true,
    "github.copilot.chat.agentSkills.enabled": true,
    "github.copilot.chat.experimental.agents": true,
    "github.copilot.chat.codeGeneration.useInstructionFiles": true,

    "files.exclude": {
      ".checkpoints/**": true
    },

    "search.exclude": {
      ".checkpoints/**": true,
      "docs/agent-telemetry/current-sprint.md": false
    },

    "editor.formatOnSave": true,

    "sdlc-copilot.plugin": {
      "workspaceManifest": ".github/copilot/workspace-manifest.json",
      "agentsDir": ".github/agents",
      "instinctsIndex": ".copilot/instincts/INDEX.json",
      "checkpointsDir": ".checkpoints",
      "telemetryFile": "docs/agent-telemetry/current-sprint.md",
      "evalsDir": "evals"
    }
  },
  "extensions": {
    "recommendations": [
      "GitHub.copilot",
      "GitHub.copilot-chat"
    ]
  }
}
WSEOF
    echo "  [add]  ${ws_name}.code-workspace"
  else
    echo "  [skip] ${ws_name}.code-workspace"
  fi

  # ════════════════════════════════════════════════════════════════════════════
  #  GETTING-STARTED.md — quick-start guide for developers joining the project
  # ════════════════════════════════════════════════════════════════════════════
  local gs_file="$TARGET_DIR/GETTING-STARTED.md"
  if [ ! -f "$gs_file" ]; then
    cat > "$gs_file" << GSEOF
# ${ws_name} — Developer Getting-Started Guide

> **Purpose:** Step-by-step setup from zero to running the agentic workflow in VS Code.

---

## 1. Prerequisites

| Tool | Version |
|------|---------|
| VS Code | ≥ 1.99 |
| GitHub Copilot | Extension enabled |
| Git | ≥ 2.40 |
| Java / your runtime | as required by your services |

---

## 2. Open the Workspace

\`\`\`bash
code ${ws_name}.code-workspace
\`\`\`

This opens VS Code in multi-root workspace mode — all service repos visible in one window.

---

## 3. Domain Knowledge

Before running agents, create your domain context:

\`\`\`bash
# Create a context file describing your domain
cp contexts/README.md contexts/your-domain.md
# Edit it with terminology, business rules, data sensitivity
\`\`\`

Also create solution design docs in \`docs/solution-design/\` — see the README.md there.

---

## 4. Run Your First Story

Open **Copilot Chat** → **Agent Mode** and invoke agents in order:

\`\`\`
@story-refiner EPIC-001
@story-analyzer EPIC-001/STORY-001
@task-planner STORY-001
@sprint-orchestrator EPIC-001
\`\`\`

Then for implementation:

\`\`\`
@local-rakbank-dev-agent implement STORY-001 phase 1
@local-reviewer review STORY-001
@address-comments STORY-001
\`\`\`

---

## 5. Session Logging

All Copilot sessions are automatically logged to \`logs/copilot/\`:
- \`session.log\` — session start/end with duration
- \`prompts.log\` — every prompt you sent with the @agent used

---

## 6. Troubleshooting

| Problem | Fix |
|---------|-----|
| Agent not visible in @-mention | Check \`.github/agents/*.agent.md\` exists and reload VS Code |
| Missing context errors | Create \`contexts/your-domain.md\` |
| No task plan created | Ensure \`taskPlan/\` directory exists (run installer again) |
| Hook not firing | Check \`.github/hooks/session-logger.json\` exists |

---

Generated by SDLC Copilot Template installer.
GSEOF
    echo "  [add]  GETTING-STARTED.md"
  else
    echo "  [skip] GETTING-STARTED.md"
  fi

  # ════════════════════════════════════════════════════════════════════════════
  #  Initialization stamp
  # ════════════════════════════════════════════════════════════════════════════
  local init_flag="$TARGET_DIR/.github/copilot/.initialized"
  if [ ! -f "$init_flag" ]; then
    echo "{\"workspace\":\"$ws_name\",\"initializedAt\":\"$(date -u +%Y-%m-%dT%H:%M:%SZ)\",\"plugin\":\"workspace\"}" \
      > "$init_flag"
    echo "  [add]  .github/copilot/.initialized"
  else
    echo "  [skip] .github/copilot/.initialized (already initialized)"
  fi

  echo ""
}
